---
title: "BMS 225a Workshop 2"
author: "Madeline McCanne"
date: "2023-10-12"
output:
  html_document:
    df_print: paged
  html_notebook: default
  pdf_document: default
---


```{r load library}
library(tidyverse)
```

```{r read csv}
# "../" goes one step up
sf_weather<- read.csv("../raw_data/sf_weather_2023.csv")

#see first six rows of data
head(sf_weather) 

#see column names
colnames(sf_weather)
```

```{r Subset the data}
#just show the DATE column
select(sf_weather, DATE)

#pipe operator, equivalent to above function. Take output of one and nest or pipe it to other functions 
date<- sf_weather %>%
  select(DATE)

head(date)
```

```{r Subset and split up data}
sf_weather_temp <- sf_weather %>% 
  select(c(DATE, TMAX, TMIN)) %>% 
  na.omit() %>% 
  separate(DATE, c("YEAR", "MONTH", "DAY"), sep="-", remove = FALSE) %>% 
  filter(YEAR=="2021") %>% 
  mutate(TAVG=((TMAX + TMIN)/2)) %>% #add new column 
  group_by(MONTH) %>% #group by month for subsequent operation
  summarize(MAX_MO_TEMP = max(TAVG))


head(sf_weather_temp)


```

```{r Plotting our data}
plot(sf_weather_temp)
```

```{r Apply functions}
#create function that summarizes maximum monthly average temperature for any given specified year. This way I don't have to rewrite the entire code chunk above for each new year
yearly_subsetter <- function(year){
  year_subset <- sf_weather %>% 
    select(c(DATE, TMAX, TMIN)) %>% 
    na.omit() %>% 
    separate(DATE, c("YEAR", "MONTH", "DAY"), sep="-", remove = FALSE) %>% 
    filter(YEAR== year) %>% 
    mutate(TAVG=((TMAX + TMIN)/2)) %>% #add new column 
    group_by(MONTH) %>% #group by month for subsequent operation
    summarize(MAX_MO_TEMP = max(TAVG))
  
  return(year_subset)
}
 yearly_subsetter("2020")
```

```{r}
year_var <- "1980"

yearly_subsetter(year = year_var)
plot(yearly_subsetter(year = year_var), main=year_var)
```

```{r Apply Function with Loops, fig.height=6, fig.width=4}
for(my_year_var in c("1970","1980", "1990", "2000")){
  plot(yearly_subsetter(year = my_year_var), main = my_year_var)
}
```

